### Parameters expected to be changed under normal use ###
## INPUT DATA AND FORMATTING ##
# formatted input file; described in README
jobname: illumina_pilot 
metaT_sample: /data/gent/vo/001/gvo00125/vsc43619/eukrhythmic/input/input.txt
spikefile: 0
spiketable: 0 
adapter:
# DIRECTORIES DURING PROCESSING ##
inputDIR: /data/gent/vo/001/gvo00125/vsc43619/raw
outputDIR: /data/gent/vo/001/gvo00125/vsc43619/illumina_pilot_eukrhythmic
assembledDIR: /data/gent/vo/001/gvo00125/vsc43619/assembly_eukrhythmic
renamedDIR: /data/gent/vo/001/gvo00125/vsc43619/renamed
# this is where all the intermediate outputs will go.
scratch:  /data/gent/vo/001/gvo00125/vsc43619/testscratch
## ANALYSIS OPTIONS ##
kegg: 
kegg_prot_db: 
busco:
    - https://www.dropbox.com/s/uqbag10d3soks68/eukaryota_odb10.2019-11-20.tar.gz?dl=1
pfam: ftp://ftp.ebi.ac.uk/pub/databases/Pfam/current_release/Pfam-A.hmm.gz

# 1 indicates that "spikefile" is used to clean reads
runbbmap: 0
# flag to be used to decide whether QUAST/salmon quantification performed
checkqual: 1
kmers:
    - 31
    - 50
    - 110
assemblers:
    - megahit
#    - velvet
    - spades
    - trinity
    - transabyss
separategroups: 0

### Parameters only to be changed by advanced users ###
transdecodercutoff: 50
secondclustercutoff: 0.98
defaultkmer: 25
mincontig: 100
rewritecluster: 0
